### ISSUE TITLE
Setup.py Extension for Visual Studio Code did not work Chat GPT gave me the solution ; ) 

### ISSUE THREAD

**Issue by artikcoder** [CoderEgloo/py2app#1]
**import sys**
from setuptools import setup
APP = ['folderorganiser_app.py']
OPTIONS = {
    'iconfile':'icon.icns',
    'argv_emulation': True,
}

**sys.argv.append('py2app')**

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

Bold lines were missing. Why?

**Comment by CoderEgloo** [comment]
The documentation shows that **import sys** and **sys.argv.append('py2app')** are not needed.

https://py2app.readthedocs.io/en/latest/examples.html

It might be specific to your application; try generating a setup.py from the module using the "python setup.py py2app" or "python3 setup.py py2app" command in the terminal.

**Comment by artikcoder** [comment]
Result: 

**python3 setup.py py2app**

/usr/local/bin/python3 "/Users/dirk/Library/CloudStorage/GoogleDrive-d.bruenner@leitmotiv.de/Meine Ablage/privat/Weiterbildung/Programmierung/uebungen/PythonAppDownloadOrdner/setup.py"
➜  PythonAppDownloadOrdner /usr/local/bin/python3 "/Users/dirk/Library/CloudStorage/GoogleDrive-d.bruenner@leitmotiv.de/Meine Ablage/privat/Weiterbildung/Prog
rammierung/uebungen/PythonAppDownloadOrdner/setup.py"
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
➜  PythonAppDownloadOrdner 




===========================================

**python setup.py py2app**

/usr/local/bin/python3 "/Users/dirk/Library/CloudStorage/GoogleDrive-d.bruenner@leitmotiv.de/Meine Ablage/privat/Weiterbildung/Programmierung/uebungen/PythonAppDownloadOrdner/setup.py"
➜  PythonAppDownloadOrdner /usr/local/bin/python3 "/Users/dirk/Library/CloudStorage/GoogleDrive-d.bruenner@leitmotiv.de/Meine Ablage/privat/Weiterbildung/Prog
rammierung/uebungen/PythonAppDownloadOrdner/setup.py"
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
➜  PythonAppDownloadOrdner /usr/local/bin/python3 "/Users/dirk/Library/CloudStorage/GoogleDrive-d.bruenner@leitmotiv.de/Meine Ablage/privat/Weiterbildung/Prog
rammierung/uebungen/PythonAppDownloadOrdner/setup.py"
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
➜  PythonAppDownloadOrdner

**Comment by CoderEgloo** [comment]
This shows that it is an error from your end, which could be anything from your file organizer application to the way your directory is set up. I would recommend looking at the py2app documentation or trying the Pyinstaller module. My extension is just supposed to provide a shortcut instead of creating the file yourself.
